#version 450

layout(set = 0, binding=0) readonly buffer b0 { float x[]; };
layout(set = 1, binding=0)          buffer b1 { float y[]; };

// pos and size are (row,col), like safetensors use
uint tensor2d_pos(uvec2 pos, uvec2 sz) {
  // This is confusing to implement, so it gets easier to use
  uint x = pos.y;
  uint y = pos.x;
  uint w = sz.y;
  return x + y * w;
}

#define T(t, p, s0, s1) t[tensor2d_pos(p, uvec2(s0, s1))]

void main() {
  uvec2 pos = gl_GlobalInvocationID.xy;
  T(y, pos, 1024, 768) += T(x, pos, 1024, 768);
}
