#version 450

layout(set=0, binding=0)          buffer in0 { float h    []; };
layout(set=1, binding=0) readonly buffer in1 { uint  indir[]; };

layout(local_size_y = 1024) in;

shared float x[1024];
shared float y[1024];

void main() {
  uint id = indir[0] - 1;
  uint lid = gl_LocalInvocationID.y;

  x[lid] = h[lid];
  memoryBarrierShared();

  float mx = x[0];
  for (int i = 1; i <= id; i++) mx = max(mx, x[i]);
  y[lid] = exp(x[lid] - mx);
  memoryBarrierShared();

  float sum = 0;
  for (int i = 0; i <= id; i++) sum += y[i];
  h[lid] = y[lid] / sum;
}

