#version 450

layout(set = 0, binding=0) readonly buffer b0 { float x[]; };
layout(set = 1, binding=0)          buffer b1 { uint y[]; };

void main() {
  uint xi = gl_GlobalInvocationID.x * 256;
  float mx = x[xi];
  uint mid = 0;
  for (int i = 0; i < 256; i++, xi++) {
    if (xi >= 50257) continue;
    if (mx < x[xi]) continue;
    mid = xi;
    mx = x[xi];
  }
  y[gl_GlobalInvocationID.x] = mid;
}
