#version 450

layout(set = 0, binding=0) readonly buffer b0 { float x[]; };
layout(set = 1, binding=0) readonly buffer b1 { uint idx[]; };
layout(set = 2, binding=0)          buffer b2 { uint y[]; };
layout(set = 3, binding=0) readonly buffer b3 { uint indir[]; };

void main() {
  uint n = indir[0];

  uint mid = idx[0];
  float mx = x[mid];
  for (int i = 0; i < 256; i++) {
    if (mx >= x[idx[i]]) continue;
    mid = idx[i];
    mx = x[mid];
  }

  y[n] = mid;
}
