#version 450

layout(set = 0, binding=0) readonly buffer b0 { float x[]; };
layout(set = 1, binding=0)          buffer b1 { uint y[]; };

void main() {
  uint mid = 0;
  float mx = -1e10;
  for (int i = 0; i < 256; i++) {
    uint xi = gl_GlobalInvocationID.x * 256 + i;
    if (xi >= 50257) continue;
    if (mx >= x[xi]) continue;
    mid = xi;
    mx = x[mid];
  }
  y[gl_GlobalInvocationID.x] = mid;
}
