#version 450

layout(set = 0, binding=0) buffer b0 { float mlp[]; };

// pos and size are (row,col), like safetensors use
uint tensor2d_pos(uvec2 pos, uvec2 sz) {
  // This is confusing to implement, so it gets easier to use
  uint x = pos.y;
  uint y = pos.x;
  uint w = sz.y;
  return x + y * w;
}

#define T(t, p, s0, s1) t[tensor2d_pos(p, uvec2(s0, s1))]

const float k = sqrt(2 / 3.1415926535);

void main() {
  uvec2 pos = gl_GlobalInvocationID.xy;
  float x = T(mlp, pos, 1024, 3072);
  T(mlp, pos, 1024, 3072) = (1 + tanh((x*x*x * 0.044715 + x) * k)) * x * 0.5;
}
