#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable

layout(set=0, binding=0) readonly buffer in0 { float a[]; };
layout(set=1, binding=0)          buffer in1 { float b[]; };

layout(local_size_y = 1024) in;

shared float x[1024];
shared float y[1024];

void main() {
  uint lid = gl_LocalInvocationID.y;
  uint gid = gl_GlobalInvocationID.x * 1024 + lid;

  x[lid] = a[gid];
  memoryBarrierShared();

  float mx = x[0];
  for (int i = 1; i < 1024; i++) mx = max(mx, x[i]);
  y[lid] = exp(x[lid] - mx);
  memoryBarrierShared();

  float sum = 0;
  for (int i = 0; i < 1024; i++) sum += y[i];
  b[gid] = y[lid] / sum;
}

