#version 450
#extension GL_EXT_shader_atomic_float : require

layout(set = 0, binding=0) readonly buffer b0 { float x[]; };
layout(set = 1, binding=0) readonly buffer b1 { float m[]; };
layout(set = 2, binding=0)          buffer b2 { float v[]; };

// pos and size are (row,col), like safetensors use
uint tensor2d_pos(uvec2 pos, uvec2 sz) {
  // This is confusing to implement, so it gets easier to use
  uint x = pos.y;
  uint y = pos.x;
  uint w = sz.y;
  return x + y * w;
}
#define T(t, p, s0, s1) t[tensor2d_pos(p, uvec2(s0, s1))]

void main() {
  float mean = m[gl_GlobalInvocationID.x] / gl_NumWorkGroups.y;
  float xi = T(x, gl_GlobalInvocationID.xy, 1024, 768);
  atomicAdd(v[gl_GlobalInvocationID.x], (xi - mean) * (xi - mean));
}
